-- 0033 down — remove the Phase-A DeFindex vault seed rows.

BEGIN;

DELETE FROM routers
 WHERE contract_id IN (
       'CDB2WMKQQNVZMEBY7Q7GZ5C7E7IAFSNMZ7GGVD6WKTCEWK7XOIAVZSAP',
       'CC5CE6MWISDXT3MLNQ7R3FVILFVFEIH3COWGH45GJKL6BD2ZHF7F7JVI',
       'CDPWNUW7UMCSVO36VAJSQHQECISPJLCVPDASKHRC5SEROAAZDUQ5DG2Z'
   )
   AND auto_discovered = false;

COMMIT;
