-- 0087 down — drop the asset_volume_24h rollup.
--
-- Revert the code FIRST; this down is not safe under a binary that reads
-- the table. The /v1/assets listing SQL names asset_volume_24h directly
-- (its per_asset_24h_vol CTE and the discovered-asset EXISTS bound), and a
-- missing relation is a 42P01 (undefined_table) query error, not an empty
-- CTE: with the table absent the listing query fails instead of rendering
-- volume_24h_usd absent. ContractCatalogueRows and the refresher
-- (RefreshAssetListingRollups) fail the same way. The pre-0087 live
-- per-request SUM is not auto-restored (the CTE now reads the rollup):
-- deploy a binary predating 0087, then run this down.
DROP TABLE IF EXISTS asset_volume_24h;
