-- 0174 up — NEUTRALISED in v0.92.1: this file is a no-op.
--
-- As shipped in v0.92.0 it decompressed every sep41_transfers chunk and
-- added the CHECK below in one implicit transaction. On r1 that is 32
-- chunks, 55 GB compressed and 780 GB decompressed: it cannot finish
-- under the deploy's 5-minute statement_timeout, and failing leaves the
-- DB dirty at 174 with 0164/0166 already committed. No environment we
-- operate had applied it (r1, testnet and futurenet all measured at
-- schema_migrations 162, 2026-09-28), so the body is neutralised under
-- the migrations/README.md "Neutralising an unapplied migration"
-- exception. The number and both files stay: golang-migrate cannot
-- advance a database whose current version has no file.
--
-- The row contract is enforced by validateSEP41TransferRows
-- (internal/storage/timescale/sep41_transfers.go) on both writers, and
-- that function mirrors the CHECK exactly. A database that applied the
-- v0.92.0 body keeps the CHECK, which is a superset of that contract and
-- is fine. Adding the CHECK everywhere is a later offline operator step
-- (pause compression, decompress chunk by chunk under a WAL guard, ADD
-- CONSTRAINT, recompress) that must first test pg_constraint for
-- sep41_transfers_amount_check, because a v0.92.0 database already has it.
--
-- The original header follows, kept for the record; it describes the
-- v0.92.0 body, not this one.
--
-- (v0.92.0) 0174 up — CHECK sep41_transfers.amount (T090).
--
-- 0047 declared `amount numeric` with no constraint, unlike its sibling
-- sep41_supply_events (0015: NOT NULL CHECK (amount >= 0)). The per-row
-- writer (InsertSEP41TransferBatch) rejected a negative or missing
-- transfer/approve amount, but the ch-rebuild COPY path
-- (CopyMergeSEP41Transfers) wrote whatever it was handed, and the table
-- itself accepted it. SEP-41 amounts are non-negative: the kind and the
-- from/to columns carry direction, so a negative amount inverts every
-- net-position sum it reaches.
--
-- The constraint mirrors the Go row contract exactly: transfer and approve
-- rows carry a non-NULL amount; set_admin / set_authorized carry none
-- (NULL); any amount present is >= 0.
--
-- sep41_transfers is a compressed hypertable, and on timescaledb 2.26.4 a
-- CHECK over the numeric `amount` column cannot be added while compressed
-- chunks exist: the ALTER fails with a corrupted-plan error ("invalid attnum
-- 64", "unrecognized node type", "stack depth limit exceeded"), NOT VALID
-- included. So this uses the 0101/0142/0148 decompress-every-chunk step
-- first; the compression policy recompresses them on its next run, and the
-- integration test pins that recompression and compressed-chunk inserts
-- both honour the CHECK. No explicit BEGIN, matching 0148: golang-migrate
-- runs the file as one implicit transaction.
--
-- If apply fails with sep41_transfers_amount_check violated, a row written
-- by the old COPY path is negative or missing its amount. Re-derive that
-- window (`stellarindex-ops projector-replay -config PATH -source
-- sep41_transfers -from <ledger>`); do not delete rows to get past it.
--
-- The v0.92.0 body, recorded so it is recognised, never to be run inside
-- a deploy:
--
--   DO NOT RUN: SELECT decompress_chunk(c, true) FROM show_chunks('sep41_transfers') c;
--   DO NOT RUN: ALTER TABLE sep41_transfers ADD CONSTRAINT sep41_transfers_amount_check
--       CHECK ((amount IS NULL OR amount >= 0)
--              AND (event_kind NOT IN ('transfer', 'approve') OR amount IS NOT NULL));

SELECT 1;
