-- 0211 up — persist the late-write window the trades caggs still owe a
-- refresh, so a crash cannot drop it.
--
-- pipeline.LateTradeRefresher refreshes a continuous aggregate over trades
-- written older than its refresh policy reaches back. It kept that window
-- only in memory, so a SIGKILL, OOM or drain-timeout exit lost it, and the
-- late rows' buckets stayed unmaterialised for good: no policy revisits
-- them.
--
-- The writer records the window here BEFORE the trade insert. A crash in
-- between leaves a window over rows that never landed; refreshing it is a
-- no-op. The next process unions every row into its first flush. A row is
-- deleted only after its view's refresh succeeds, and only while gen still
-- holds the value read before that refresh; any widen sets a new gen, so a
-- write landing mid-refresh keeps its window pending.
--
-- One row per (family, view), so one failing view cannot pin the others.
-- Only 'trades' has a writer today; 'oracle' is reserved for the oracle
-- caggs.
--
-- Additive: an old binary ignores the table (migrations/README.md rule 9).

BEGIN;

CREATE TABLE IF NOT EXISTS cagg_late_refresh_windows (
    family     text        NOT NULL CHECK (family IN ('trades', 'oracle')),
    view       text        NOT NULL,
    from_ts    timestamptz NOT NULL,
    to_ts      timestamptz NOT NULL,
    first_seen timestamptz NOT NULL DEFAULT now(),
    gen        bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (family, view),
    CHECK (to_ts >= from_ts)
);

COMMENT ON TABLE cagg_late_refresh_windows IS
    'Per continuous aggregate, the trade-time window of rows written older '
    'than its refresh policy reaches back that no refresh has materialised '
    'yet. Written only by the indexer''s pipeline.LateTradeRefresher, before '
    'the insert; deleted by it once that view''s refresh succeeds and gen '
    'is unchanged.';

COMMENT ON COLUMN cagg_late_refresh_windows.from_ts IS
    'Inclusive lower bound of the late rows'' timestamps, floored to the hour.';

COMMENT ON COLUMN cagg_late_refresh_windows.to_ts IS
    'Upper bound of the late rows'' timestamps, ceiled to the hour.';

COMMENT ON COLUMN cagg_late_refresh_windows.first_seen IS
    'When the oldest unrefreshed write was recorded; drives the overdue alert '
    'across restarts.';

COMMENT ON COLUMN cagg_late_refresh_windows.gen IS
    'Fresh identity value on every insert or widen. The delete matches the '
    'gen read before the refresh, so a widen during it survives.';

COMMIT;
