#!/usr/bin/env bash
# ch-schema-snapshot.sh — ADR-0043 §2.1, the ClickHouse lake's actual
# backup.
#
# ADR-0043 REJECTS a full CH backup as the primary strategy: the lake's
# ground truth (raw LCM) already exists in two independent archives, so
# paying object storage for a third copy of derived data is poor spend.
# What it commits to instead is this — "Schema + state backup (tiny,
# daily): SHOW CREATE DDL for every table + the ch-live-catchup/backfill
# cursor state, pushed to repo2 alongside pgBackRest. Losing DDL/config
# is what turns a re-derive from 'run the script' into archaeology."
#
# That sentence is the whole justification. The re-derive machinery is
# committed code and the raw ledgers are in two archives — but the lake's
# 40-odd table definitions, their ORDER BY / PARTITION BY keys, codecs,
# TTLs, materialized views and the exact set of 1M-ledger partitions that
# existed are NOT reconstructible from anything in the repo. tier1_schema.sql
# is the FOUNDING DDL, not the live one: indexes, MVs, compression policies
# and serving-profile changes have landed on top of it since. Restoring
# from a stale hand-written schema silently changes the sort order of a
# 60M-ledger rebuild.
#
# Emits (node_exporter textfile collector, so the freshness of the backup
# is itself alerted — a silent backup is the failure class this whole ADR
# exists for):
#   stellarindex_ch_schema_snapshot_last_success_unix
#   stellarindex_ch_schema_snapshot_tables
#   stellarindex_ch_schema_snapshot_bytes
#   stellarindex_ch_schema_snapshot_offsite_configured (1 iff SNAPSHOT_MC_TARGET
#     is set — emitted EVERY run so the offsite alert can tell "never
#     pushed" from "acked local-only")
#   stellarindex_ch_schema_snapshot_offsite_last_success_unix (push only)
# Alerts: stellarindex_ch_schema_snapshot_stale /
#         stellarindex_ch_schema_snapshot_offsite_stale /
#         stellarindex_ch_schema_snapshot_unit_failed (storage.yml, both trees).
#
# Restore path: docs/operations/runbooks/ch-schema-restore.md.
#
# Usage:
#   ch-schema-snapshot.sh                       # daily timer shape
#   OUT_DIR=./deploy/clickhouse/schema-snapshot \
#     TEXTFILE_DIR=/dev/null ch-schema-snapshot.sh   # regenerate the in-repo copy
#
# Exit code: 0 clean; 1 the snapshot itself failed (nothing usable
# written); 2 the snapshot was written but the offsite push failed.
set -uo pipefail

CH_HTTP="${CH_HTTP:-http://127.0.0.1:8123/}"
CH_DATABASE="${CH_DATABASE:-stellar}"
OUT_DIR="${OUT_DIR:-/var/lib/stellarindex/ch-schema-snapshot}"
TEXTFILE_DIR="${TEXTFILE_DIR:-/var/lib/node_exporter/textfile_collector}"
RETAIN_DAYS="${RETAIN_DAYS:-90}"
BACKFILL_STATE="${BACKFILL_STATE:-/var/lib/ch-backfill/done-windows.txt}"
PG_DSN="${STELLARINDEX_POSTGRES_DSN:-}"
# Offsite target, gated on presence — exactly the pgbackrest_repo2 idiom
# (18-pgbackrest-backup.yml): unset means local-only and the role has to
# have carried an explicit ack for that. An `mc` alias/prefix, e.g.
# "offsite/stellarindex-backups/ch-schema".
SNAPSHOT_MC_TARGET="${SNAPSHOT_MC_TARGET:-}"

stamp="$(date -u +%Y%m%dT%H%M%SZ)"
day="$(date -u +%F)"
work="$OUT_DIR/$day"
rc=0
snapshot_ok=1

note() { echo "ch-schema-snapshot: $*" >&2; }
ch() { curl -sSf --max-time 120 "$CH_HTTP" --data-binary "$1"; }
# A partial capture must not stamp a fresh last_success: half a schema
# presented as a backup is the exact "we thought we had one" failure
# ADR-0043 was written after. Degrade -> the staleness alert fires.
degrade() { note "$1"; snapshot_ok=0; rc=1; }

mkdir -p "$work" || { note "cannot create $work"; exit 1; }

# ─── 1. the tables ──────────────────────────────────────────────────
# system.tables covers tables, materialized views and dictionaries in
# one list, which is what a restore needs — an MV that is missing after
# a rebuild is a silently empty serving surface, not an error.
tables="$(ch "SELECT name FROM system.tables
             WHERE database = '$CH_DATABASE' AND NOT is_temporary
             ORDER BY name FORMAT TabSeparated")" || {
  note "cannot list tables in database '$CH_DATABASE' via $CH_HTTP"
  exit 1
}
table_count="$(grep -c . <<<"$tables")"
if [[ "$table_count" -eq 0 ]]; then
  # Fail closed. An empty snapshot that overwrites a good one is worse
  # than no snapshot: it turns "we have a backup" into a lie, quietly,
  # on the exact day the database was unreachable.
  note "database '$CH_DATABASE' reported ZERO tables — refusing to write an empty snapshot"
  exit 1
fi

schema="$work/schema.sql"
{
  echo "-- ClickHouse schema snapshot — $stamp"
  echo "-- database: $CH_DATABASE, tables: $table_count"
  echo "-- Generated by scripts/ops/ch-schema-snapshot.sh (ADR-0043 §2.1)."
  echo "-- Restore: docs/operations/runbooks/ch-schema-restore.md"
  echo
  echo "CREATE DATABASE IF NOT EXISTS $CH_DATABASE;"
  echo
} > "$schema"
while IFS= read -r t; do
  [[ -z "$t" ]] && continue
  if ! ch "SHOW CREATE TABLE \`$CH_DATABASE\`.\`$t\` FORMAT TabSeparatedRaw" >> "$schema"; then
    degrade "SHOW CREATE failed for $CH_DATABASE.$t"
  fi
  printf ';\n\n' >> "$schema"
done <<<"$tables"
if [[ "$snapshot_ok" -ne 1 ]]; then
  # A DDL file missing tables is the archaeology case this exists to
  # prevent, dressed as a success. Leave the directory for diagnosis but
  # do NOT stamp a fresh last_success — the staleness alert must fire.
  note "one or more SHOW CREATE statements failed — snapshot is INCOMPLETE"
  exit 1
fi

# ─── 2. the schema-relevant state ───────────────────────────────────
# Engine/keys inventory: human-readable cross-check that the restored
# DDL is the one that was live, plus the row/byte counts a rebuild is
# sized against.
ch "SELECT name, engine, partition_key, sorting_key, total_rows, total_bytes
    FROM system.tables WHERE database = '$CH_DATABASE' AND NOT is_temporary
    ORDER BY name FORMAT TabSeparatedWithNames" > "$work/tables.tsv" \
  || degrade "tables inventory query failed"

# Which 1M-ledger partitions existed, and how big. This is the
# difference between "rebuild everything" and "rebuild these 12
# partitions" when a restore is partial.
ch "SELECT table, partition, sum(rows) AS rows, sum(bytes_on_disk) AS bytes
    FROM system.parts WHERE database = '$CH_DATABASE' AND active
    GROUP BY table, partition ORDER BY table, partition
    FORMAT TabSeparatedWithNames" > "$work/partitions.tsv" \
  || degrade "partition inventory query failed"

# Non-default server settings: a rebuild under different settings can
# behave differently enough to matter (merge behaviour, memory caps).
ch "SELECT name, value FROM system.settings WHERE changed ORDER BY name
    FORMAT TabSeparatedWithNames" > "$work/settings-changed.tsv" \
  || degrade "changed-settings query failed"

ch "SELECT version(), uptime() FORMAT TabSeparatedWithNames" > "$work/server.tsv" \
  || degrade "server version query failed"

# ─── 3. the cursor state (ADR-0043 §2.1's second half) ──────────────
# ch-full-backfill.sh banks a window as done ONLY on ch-backfill exit 0
# and never revisits it, so this file IS the record of what has been
# backfilled. Losing it means re-walking 60M ledgers to find out.
if [[ -r "$BACKFILL_STATE" ]]; then
  cp "$BACKFILL_STATE" "$work/ch-backfill-done-windows.txt"
else
  note "backfill state $BACKFILL_STATE not readable — recording its absence"
  echo "# $BACKFILL_STATE was not readable at $stamp" > "$work/ch-backfill-done-windows.txt"
fi

# ch-live-catchup reads its tip from Postgres ingestion_cursors. That
# table is inside the pgBackRest stanza already, but a CH-side rebuild
# should not need a full Postgres restore to learn where the live sink
# had got to.
if [[ -n "$PG_DSN" ]] && command -v psql >/dev/null 2>&1; then
  psql "$PG_DSN" -tAF$'\t' -c \
    "SELECT source, sub_source, last_ledger, updated_at FROM ingestion_cursors ORDER BY source, sub_source" \
    > "$work/ingestion-cursors.tsv" 2>/dev/null || {
      note "ingestion_cursors read failed — continuing (pgBackRest covers this table)"
      rm -f "$work/ingestion-cursors.tsv"
    }
fi

# ─── 4. manifest + retention ────────────────────────────────────────
{
  echo "snapshot: $stamp"
  echo "database: $CH_DATABASE"
  echo "tables: $table_count"
  echo "host: $(hostname -f 2>/dev/null || hostname)"
  echo "generator: scripts/ops/ch-schema-snapshot.sh (ADR-0043 §2.1)"
} > "$work/MANIFEST"
( cd "$work" && sha256sum -- * > SHA256SUMS 2>/dev/null ) || true

bytes="$(du -sb "$work" 2>/dev/null | cut -f1)"
bytes="${bytes:-0}"
note "wrote $work ($table_count tables, ${bytes}B)"

# Retention: the snapshot is megabytes, so keep a long tail — the value
# of this backup is partly the DIFF history (when did that ORDER BY
# change?), which a 7-day window would throw away.
find "$OUT_DIR" -mindepth 1 -maxdepth 1 -type d -mtime "+$RETAIN_DAYS" -exec rm -rf {} + 2>/dev/null || true

# ─── 5. offsite push (gated on presence) ────────────────────────────
# ADR-0043 §2.1 says "pushed to repo2 alongside pgBackRest": a copy that
# lives only on the pool it protects is not a backup. Unset target =
# local-only, which the ansible role forces the operator to acknowledge
# explicitly (ch_schema_snapshot_offsite_ack) rather than drift into.
offsite_ok=0
if [[ -n "$SNAPSHOT_MC_TARGET" ]]; then
  if command -v mc >/dev/null 2>&1 && mc mirror --overwrite "$work" "$SNAPSHOT_MC_TARGET/$day" >/dev/null 2>&1; then
    offsite_ok=1
    note "pushed to $SNAPSHOT_MC_TARGET/$day"
  else
    note "OFFSITE PUSH FAILED to $SNAPSHOT_MC_TARGET/$day — the snapshot exists only on this host"
    rc=2
  fi
fi

# ─── 6. metrics ─────────────────────────────────────────────────────
if [[ "$TEXTFILE_DIR" != "/dev/null" ]]; then
  mkdir -p "$TEXTFILE_DIR"
  out="$TEXTFILE_DIR/ch_schema_snapshot.prom"
  tmp="$out.tmp.$$"
  {
    echo "# HELP stellarindex_ch_schema_snapshot_last_success_unix Unix time of the most recent successful ClickHouse schema+state snapshot (ADR-0043 §2.1)."
    echo "# TYPE stellarindex_ch_schema_snapshot_last_success_unix gauge"
    if [[ "$snapshot_ok" -eq 1 ]]; then
      echo "stellarindex_ch_schema_snapshot_last_success_unix $(date +%s)"
    fi
    echo "# HELP stellarindex_ch_schema_snapshot_tables Number of tables/views captured in the most recent snapshot."
    echo "# TYPE stellarindex_ch_schema_snapshot_tables gauge"
    echo "stellarindex_ch_schema_snapshot_tables $table_count"
    echo "# HELP stellarindex_ch_schema_snapshot_bytes Size on disk of the most recent snapshot directory."
    echo "# TYPE stellarindex_ch_schema_snapshot_bytes gauge"
    echo "stellarindex_ch_schema_snapshot_bytes $bytes"
    # Always emitted: the offsite staleness alert's absent-series branch
    # is gated on this so a push that has NEVER succeeded fires while an
    # acked local-only host (no target) stays silent.
    echo "# HELP stellarindex_ch_schema_snapshot_offsite_configured 1 if an offsite target (SNAPSHOT_MC_TARGET) is configured for this host, else 0."
    echo "# TYPE stellarindex_ch_schema_snapshot_offsite_configured gauge"
    if [[ -n "$SNAPSHOT_MC_TARGET" ]]; then
      echo "stellarindex_ch_schema_snapshot_offsite_configured 1"
    else
      echo "stellarindex_ch_schema_snapshot_offsite_configured 0"
    fi
    if [[ -n "$SNAPSHOT_MC_TARGET" && "$offsite_ok" -eq 1 ]]; then
      echo "# HELP stellarindex_ch_schema_snapshot_offsite_last_success_unix Unix time of the most recent successful offsite push of the schema snapshot."
      echo "# TYPE stellarindex_ch_schema_snapshot_offsite_last_success_unix gauge"
      echo "stellarindex_ch_schema_snapshot_offsite_last_success_unix $(date +%s)"
    fi
  } > "$tmp"
  chmod 644 "$tmp"
  mv "$tmp" "$out"
fi

exit "$rc"
