#!/usr/bin/env bash
# check-deprecations-test.sh — fixture tests for scripts/ci/check-deprecations.sh.
# Each case is a throwaway git repo, since the gate scans tracked files only.
#
# Run: bash scripts/ci/check-deprecations-test.sh
set -uo pipefail

cd "$(dirname "$0")/../.." || exit 1
CHECK="$PWD/scripts/ci/check-deprecations.sh"

# A pre-commit hook exports these; git init and the gate's ls-files would
# otherwise act on the real repository instead of the fixture.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
      GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

pass=0
fail=0

# shellcheck source=scripts/ci/lib/test-expect.sh
. "$PWD/scripts/ci/lib/test-expect.sh"

# run <file> <body> [<file> <body> …] — a fresh fixture repo tracking each
# file, then the gate against it.
run() {
  rm -rf "$TMP/root"
  mkdir -p "$TMP/root"
  (
    cd "$TMP/root" || exit 1
    real_dir="$(pwd -P)"
    git init -q
    case "$(git rev-parse --absolute-git-dir)" in
      "$real_dir"/*) ;;
      *) echo "fixture escaped its directory — refusing to continue" >&2; exit 1 ;;
    esac
    while [ "$#" -gt 0 ]; do
      mkdir -p "$(dirname "$1")"
      printf '%s\n' "$2" > "$1"
      git add -- "$1"
      shift 2
    done
  ) || { echo "fixture setup failed" >&2; exit 1; }
  OUT="$(bash "$CHECK" "$TMP/root" 2>&1)"
  RC=$?
}

run internal/a/a.go 'package a

// Old is the legacy form.
//
// Deprecated: use New; kept only for stored rows.
const Old = 1'
expect 'a marker naming no version fails with file:line' 1 'internal/a/a.go:5:'

run internal/a/a.go 'package a

// Deprecated: use New; kept only for stored rows.
// Will be removed in v2.0.0.
const Old = 1'
expect 'a version on a continuation line of the paragraph passes' 0 'OK'

run internal/a/a.go 'package a

// Deprecated: use New.
//
// Will be removed in v2.0.0.
const Old = 1'
expect 'a version after a blank comment line is outside the paragraph' 1 'internal/a/a.go:3:'

run internal/a/a.go 'package a

type T struct {
	// Deprecated: use B. Will be removed in v2.0.0.
	A int
	// Deprecated: use C.
	B int
}'
expect 'an indented field marker is checked on its own paragraph' 1 'internal/a/a.go:6:'

run internal/a/a.go 'package a

const Old = 1' docs/x.md '// Deprecated: prose, not Go.'
expect 'a non-Go file is ignored' 0 'OK'

run internal/a/a_gen.go '// Code generated by tool. DO NOT EDIT.

package a

// Deprecated: upstream wording.
const Old = 1'
expect 'a generated file is skipped' 0 'OK'

run docs/x.md 'nothing'
expect 'a tree with no tracked Go refuses to pass vacuously' 2 'refusing to pass vacuously'

echo
echo "check-deprecations-test: ${pass} passed, ${fail} failed"
[ "$fail" -eq 0 ] || exit 1
