#!/usr/bin/env bash
# Prove each lint-comments rule can fail, against a fixture tree outside any git checkout.
set -uo pipefail
cd "$(dirname "$0")/../.." || exit 1
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
go build -o "$T/lint" ./scripts/ci/lint-comments || exit 1
PASS=0; FAIL=0

reset() {
  rm -rf "$T/r"; mkdir -p "$T/r/internal/a" "$T/r/pkg/client" "$T/r/scripts/ci"
  printf 'package a\n\n// Why it exists.\nfunc A() {}\n' > "$T/r/internal/a/a.go"
  : > "$T/r/scripts/ci/lint-comments.baseline"
}
put() { printf 'package a\n\n%s\nfunc B() {}\n' "$2" > "$T/r/$1"; }
bl() { printf '%s\n' "$@" > "$T/r/scripts/ci/lint-comments.baseline"; }
check() { # check <name> <ok|red>
  local rc; "$T/lint" -root "$T/r" >"$T/out" 2>&1; rc=$?
  if { [ "$2" = ok ] && [ "$rc" -eq 0 ]; } || { [ "$2" = red ] && [ "$rc" -eq 1 ]; }; then
    printf '  ok   %s\n' "$1"; PASS=$((PASS+1))
  else
    printf '  FAIL %s (rc=%s, wanted %s)\n' "$1" "$rc" "$2"; sed 's/^/       /' "$T/out"; FAIL=$((FAIL+1))
  fi
}
tab=$'\t'

reset;                                                          check "clean tree with an empty baseline passes" ok
reset; put internal/a/b.go '// Fixed in INV-0001.';             check "ticket id in a product comment is rejected" red
reset; put internal/a/b.go '// Seen on 2026-01-02 in prod.';    check "date in a product comment is rejected" red
reset; put internal/a/b.go '/* see PR 12 */';                    check "PR n in a block comment is rejected" red
reset; put internal/a/b.go '// Landed in #1234.';               check "#nnn in a product comment is rejected" red
reset; put internal/a/b.go '// Landed in 1b1e46a09.';           check "commit hash in a product comment is rejected" red
reset; put internal/a/b.go '// Rate is 012087500 per unit.';    check "all-digit run is not a commit hash" ok
reset; put internal/a/b.go '// Rejects "1e999999999".';         check "float exponent is not a commit hash" ok
reset; put internal/a/b.go '// Fixed in INV-0001.'; bl "internal/a/b.go${tab}INV-0001"; check "baselined citation passes" ok
reset; put internal/a/b.go $'// INV-0001 here\n// and INV-0001 again'; bl "internal/a/b.go${tab}INV-0001"; check "second copy of a baselined citation is rejected" red
reset; bl "internal/a/b.go${tab}INV-0001";                      check "stale baseline entry is rejected" red
reset; put internal/a/b_test.go '// Fixed in INV-0001.';        check "_test.go is out of scope" ok
reset; put pkg/client/c.go '// Fixed in INV-0001.';             check "pkg/ is out of scope" ok
reset; printf '// Code generated by x. DO NOT EDIT.\n\npackage a\n\n// INV-0001\nfunc G() {}\n' > "$T/r/internal/a/g.go"; check "generated file is out of scope" ok
reset; printf 'package a\n\nvar S = "INV-0001 // 2026-01-02"\n' > "$T/r/internal/a/s.go"; check "string literal is not a comment" ok
reset; put internal/a/b.go '// Layout is 2006-01-02.';          check "Go reference layout is not a date citation" ok
reset; put internal/a/b.go '//go:generate echo INV-0001';       check "go: directive is not a comment line" ok
reset; put internal/a/b.go '// Fixed in INV-0001.'; "$T/lint" -root "$T/r" -write >/dev/null; check "-write records the tree" ok

echo "lint-comments self-test: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
