#!/usr/bin/env bash
# lint-repo-budget-test.sh — prove each check in lint-repo-budget.sh can go
# red, and that its allowances stay green, against a fixture repository.
set -uo pipefail

# A hook exports GIT_DIR, and `git init` honours it over `-C`.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
      GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR

cd "$(dirname "$0")/../.." || exit 1
GATE="$PWD/scripts/ci/lint-repo-budget.sh"

# Physical path: macOS mktemp answers under a /var symlink, git reports /private/var.
TMP="$(cd "$(mktemp -d)" && pwd -P)"
trap 'rm -rf "$TMP"' EXIT

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1
export GIT_AUTHOR_NAME=fixture GIT_AUTHOR_EMAIL=fixture@example.invalid
export GIT_COMMITTER_NAME=fixture GIT_COMMITTER_EMAIL=fixture@example.invalid

R="$TMP/repo"
mkdir -p "$R"
git -C "$R" init -q
if [ "$(git -C "$R" rev-parse --show-toplevel)" != "$R" ]; then
  echo "lint-repo-budget-test: fixture escaped its directory — refusing to continue" >&2
  exit 1
fi

PASS=0; FAIL=0
expect() { # expect <name> <ok|red> <needle> [gate args...]
  local name="$1" want="$2" needle="$3" out rc
  shift 3
  out="$(cd "$R" && BASE_SHA="$base" bash "$GATE" "$@" 2>&1)"; rc=$?
  if { [ "$want" = ok ] && [ "$rc" -eq 0 ]; } || { [ "$want" = red ] && [ "$rc" -eq 1 ]; }; then
    if grep -qF -- "$needle" <<<"$out"; then
      printf '  ok   %s\n' "$name"; PASS=$((PASS+1)); return
    fi
  fi
  printf '  FAIL %s (rc=%s, wanted %s, needle %s)\n' "$name" "$rc" "$want" "$needle"
  printf '       %s\n' "$out"
  FAIL=$((FAIL+1))
}
gofile() { # gofile <path> <lines> [first-line]
  mkdir -p "$R/$(dirname "$1")"
  awk -v n="$2" -v first="${3:-package pkg}" 'BEGIN { print first; for (i = 2; i <= n; i++) print "var _ = " i }' > "$R/$1"
}
put() { # put <path> <body>
  mkdir -p "$R/$(dirname "$1")"
  printf '%s\n' "$2" > "$R/$1"
}
commit() { git -C "$R" add -A && git -C "$R" commit -q -m "$1"; }
fresh() { git -C "$R" checkout -q -B case "$base"; }

gofile pkg/a.go 10
printf '// 2025-01-01 legacy note on an untouched line\n' >> "$R/pkg/a.go"
gofile pkg/big.go 2100
gofile pkg/big_test.go 2500
gofile pkg/gen.go 2500 '// Code generated by fixture. DO NOT EDIT.'
put docs/old-2026-07.md '# old'
put docs/operations/sla-proof-2026-09-15.md '# proof'
put scripts/ci/lint-repo-budget.baseline $'# fixture\ngo-lines pkg/big.go 2100\ndated-md docs/old-2026-07.md'
commit base
base="$(git -C "$R" rev-parse HEAD)"

echo "lint-repo-budget-test: tree checks"
expect "baselined tree, exempt test/generated/sla-proof files: green" ok "lint-repo-budget: OK"

cp "$R/scripts/ci/lint-repo-budget.baseline" "$TMP/before"
(cd "$R" && bash "$GATE" --write >/dev/null)
if diff <(grep -v '^#' "$TMP/before" | LC_ALL=C sort) <(grep -v '^#' "$R/scripts/ci/lint-repo-budget.baseline") >/dev/null; then
  printf '  ok   %s\n' "--write regenerates the same entries, sorted"; PASS=$((PASS+1))
else
  printf '  FAIL %s\n' "--write regenerates the same entries, sorted"; FAIL=$((FAIL+1))
fi
cp "$TMP/before" "$R/scripts/ci/lint-repo-budget.baseline"

fresh; put docs/new-2026-09.md '# new'; commit dated
expect "a new dated .md is rejected" red "dated-md docs/new-2026-09.md"

fresh; put docs/operations/sla-proof-2026-09-22.md '# proof'; commit proof
expect "a new sla-proof-YYYY-MM-DD.md is allowed" ok "lint-repo-budget: OK"

fresh; gofile pkg/big.go 2101; commit grow
expect "a baselined .go that grew past its ceiling is rejected" red "go-lines pkg/big.go: 2101 lines, over its baselined ceiling of 2100"

fresh; gofile pkg/huge.go 2001; commit huge
expect "a new 2,001-line .go is rejected" red "go-lines pkg/huge.go: 2001 lines, over the 2000-line limit"

fresh; gofile pkg/edge.go 2000; commit edge
expect "a new 2,000-line .go is allowed" ok "lint-repo-budget: OK"

fresh; git -C "$R" rm -q pkg/big.go; commit gone
expect "a baseline entry for a deleted file is stale" red "stale go-lines pkg/big.go"

fresh; gofile pkg/big.go 1500; commit shrink
expect "a baselined file now under the limit is stale" red "stale go-lines pkg/big.go: 1500 lines"

echo "lint-repo-budget-test: added comments"
fresh; printf '// fixed in F-1234\n' >> "$R/pkg/a.go"; commit ticket
expect "an added comment citing a ticket id is rejected" red "pkg/a.go:12: added comment carries a ticket id"

fresh; printf 'var x = 1 // 2026-09-01 incident\n' >> "$R/pkg/a.go"; commit date
expect "an added trailing comment carrying a date is rejected" red "pkg/a.go:12: added comment carries a date"

fresh
{
  printf '// see ADR-0031 and SEP-41; hashes are SHA-256, text is UTF-8\n'
  printf 'var layout = "2006-01-02" // layout 2006-01-02\n'
  printf 'var u = "https://example.invalid/T-1234/2026-09"\n'
} >> "$R/pkg/a.go"
commit allowed
expect "ADR/SEP/SHA/UTF refs, the Go layout and a URL string stay green" ok "3 added Go line(s) scanned"

fresh; put pkg/b.go $'package pkg\n\n// CS-102 staged'; git -C "$R" add pkg/b.go
expect "--staged reads the index" red "pkg/b.go:3: added comment carries a ticket id" --staged

echo
echo "lint-repo-budget-test: $PASS passed, $FAIL failed"
exit "$FAIL"
