#!/usr/bin/env bash
# lint-attribution.sh — fails if a tracked doc, or a commit in the given
# range, carries an agent/vendor self-attribution marker (Co-Authored-By/
# Claude-Session trailer, a "Generated with" footer, or a bare 🤖 marker).
#
# F167/F172: the only thing that ever checked for this was
# scripts/dev/install-hooks.sh's opt-in local pre-commit hook — skippable
# with `git commit --no-verify`, absent unless a contributor ran `make
# hooks`, and blind to a web-UI commit either way. This script is invoked
# unconditionally from .github/workflows/commit-identity.yml, which carries
# no paths-ignore and always fetches full history — deliberately, because
# ci.yml's `doc-checks` job (where a tree-content doc lint would otherwise
# naturally live) never runs at all on a docs-only push: the whole ci
# workflow is skipped for a push that only touches `**.md`/`docs/**`, which
# is exactly the shape a self-attribution marker in a doc arrives as.
#
# Usage: lint-attribution.sh [<commit-range>]
#   <commit-range> — anything `git log` accepts (e.g. "$BEFORE..$SHA").
#   Tracked doc content is always checked; the commit-message scan runs
#   only when a range is given.
set -uo pipefail
cd "$(dirname "$0")/../.." || exit 1

# The specific trailer/footer SHAPES the repo forbids, not the bare word
# "claude" — this file, or an audit doc noting "no anthropic/openai
# imports", are legitimate uses. Case-insensitive throughout.
RE='co-authored-by:[^`]*claude|claude-session:|claude\.ai/code/session_|generated with \[claude|written by (an )?ai\b|help of claude|generated by claude|🤖'

bad=0

echo "Checking tracked docs for an agent/vendor self-attribution marker..."
while IFS= read -r f; do
  hit=$(grep -nEi "$RE" "$f" || true)
  [ -n "$hit" ] || continue
  while IFS=: read -r ln _; do
    echo "ERROR: $f:$ln carries an agent/vendor self-attribution marker (Co-Authored-By/Claude-Session/🤖 footer/'generated with'). Commits and docs here are authored by the contributor; strip it." >&2
    bad=$((bad + 1))
  done <<<"$hit"
done < <(git ls-files '*.md')

if [ -n "${1:-}" ]; then
  echo "Checking commit messages over range: $1 ..."
  shas=$(mktemp)
  # shellcheck disable=SC2086
  git log $1 --format='%H' 2>/dev/null >"$shas" || : >"$shas"
  while IFS= read -r sha; do
    body=$(git log -1 --format=%B "$sha" 2>/dev/null)
    grep -qEi "$RE" <<<"$body" || continue
    echo "ERROR: commit ${sha:0:12} carries an agent/vendor self-attribution marker in its message — Co-Authored-By/Claude-Session trailers and 'Generated with' footers are not repo convention; the message names the contributor only." >&2
    bad=$((bad + 1))
  done <"$shas"
  rm -f "$shas"
fi

if [ "$bad" -gt 0 ]; then
  echo "lint-attribution: $bad marker(s) found." >&2
  exit 1
fi
echo "lint-attribution: OK — no agent/vendor marker found."
