package sushiswap_v3

// Golden bodies captured read-only from the certified ClickHouse lake
// (stellar.contract_events) on 2026-09-05. Each constant is the exact
// base64 SCVal the chain emitted — no hand-edited bytes anywhere in this
// file, so a decode change that alters real-world behaviour fails the
// golden tests rather than passing against a convenient fixture.
const (
	// goldenSwapSellToken0 — pool CCR2CH4G… (XLM/USDC, 0.30%), ledger
	// 64,200,014, tx 33ccf403…1b8d, op 0, event 2. Post-upgrade WASM.
	// The trader sold token0 (XLM) and bought token1 (USDC).
	goldenSwapSellToken0 = "AAAAEQAAAAEAAAAHAAAADwAAAAdhbW91bnQwAAAAAAoAAAAAAAAAAAAAAAKbkBKCAAAADwAAAAdhbW91bnQxAAAAAAr///////////////+IvljzAAAADwAAAAlsaXF1aWRpdHkAAAAAAAAJAAAAAAAAAAAAABT7VCUfkAAAAA8AAAAJcmVjaXBpZW50AAAAAAAAEgAAAAAAAAAAg4eXTqvln7UyuhyGiCx0mY+jynWO/Nd+cfjj9joHtjUAAAAPAAAABnNlbmRlcgAAAAAAEgAAAAAAAAAAg4eXTqvln7UyuhyGiCx0mY+jynWO/Nd+cfjj9joHtjUAAAAPAAAADnNxcnRfcHJpY2VfeDk2AAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAABsWnxia7eHCEjg07kAAAAPAAAABHRpY2sAAAAE//+80w=="

	// goldenSwapSellToken1 — same pool, ledger 64,200,958,
	// tx 6dccaebd…fe1d, op 0, event 2. The opposite direction: the trader
	// sold token1 (USDC) and bought token0 (XLM).
	goldenSwapSellToken1 = "AAAAEQAAAAEAAAAHAAAADwAAAAdhbW91bnQwAAAAAAr///////////////2rcVW2AAAADwAAAAdhbW91bnQxAAAAAAoAAAAAAAAAAAAAAABn261QAAAADwAAAAlsaXF1aWRpdHkAAAAAAAAJAAAAAAAAAAAAABT/pVmN9AAAAA8AAAAJcmVjaXBpZW50AAAAAAAAEgAAAAAAAAAAJB/6WJIl4kbG0JuQFoHF0vDAhPVAOyZmcjYRjEFqGvEAAAAPAAAABnNlbmRlcgAAAAAAEgAAAAAAAAAAJB/6WJIl4kbG0JuQFoHF0vDAhPVAOyZmcjYRjEFqGvEAAAAPAAAADnNxcnRfcHJpY2VfeDk2AAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAABqqiy42aaCFuU64usAAAAPAAAABHRpY2sAAAAE//+7mQ=="

	// goldenSwapPreUpgrade — same pool, ledger 61,493,095,
	// tx f6fb00ef…c308, op 0, event 14. Emitted by the ORIGINAL pool WASM,
	// before the factory-driven upgrades at ledgers 61,594,973 and
	// 62,898,378. Proves one decoder covers the full history.
	goldenSwapPreUpgrade = "AAAAEQAAAAEAAAAHAAAADwAAAAdhbW91bnQwAAAAAAoAAAAAAAAAAAAAAAAFuAFpAAAADwAAAAdhbW91bnQxAAAAAAr/////////////////CT5hAAAADwAAAAlsaXF1aWRpdHkAAAAAAAAJAAAAAAAAAAAAAAAAHZIo3QAAAA8AAAAJcmVjaXBpZW50AAAAAAAAEgAAAAAAAAAAxRy/OA51yJ4u3YL0mKNf2jKqkAy3kYfYMFIdzMphcBgAAAAPAAAABnNlbmRlcgAAAAAAEgAAAAAAAAAAxRy/OA51yJ4u3YL0mKNf2jKqkAy3kYfYMFIdzMphcBgAAAAPAAAADnNxcnRfcHJpY2VfeDk2AAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAABlKxxd8TMIn9sIRdQAAAAPAAAABHRpY2sAAAAE//+3dw=="

	// goldenSwapNonDirectional — same pool, ledger 62,712,211,
	// tx c485886b…c6b1, op 0, event 23. amount0=1, amount1=0: a one-unit
	// dust swap whose output rounded to nothing. The ONLY non-directional
	// swap in the protocol whole-history sweep (1 of 97,349).
	goldenSwapNonDirectional = "AAAAEQAAAAEAAAAHAAAADwAAAAdhbW91bnQwAAAAAAoAAAAAAAAAAAAAAAAAAAABAAAADwAAAAdhbW91bnQxAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAlsaXF1aWRpdHkAAAAAAAAJAAAAAAAAAAAAAFR1m4fYNAAAAA8AAAAJcmVjaXBpZW50AAAAAAAAEgAAAAG9AFfpIbrMRk93c+6TptM5kPuBIbWbozdfezhPfUjRpQAAAA8AAAAGc2VuZGVyAAAAAAASAAAAAb0AV+khusxGT3dz7pOm0zmQ+4EhtZujN197OE99SNGlAAAADwAAAA5zcXJ0X3ByaWNlX3g5NgAAAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAYr8YxM6DxyxqMW+4AAAADwAAAAR0aWNrAAAABP//tZI="

	// goldenPoolCreated — factory CD3KRKGD…, ledger 61,487,379,
	// tx 01d797bc…4765, op 0, event 0. Creates the XLM/USDC 0.30% pool.
	goldenPoolCreated = "AAAAEQAAAAEAAAAGAAAADwAAAANmZWUAAAAAAwAAC7gAAAAPAAAADHBvb2xfYWRkcmVzcwAAABIAAAABo6EfhoVFk5viOWrGgaJXOip0dVXyhCJjzAFNiInP4wMAAAAPAAAABnNlbmRlcgAAAAAAEgAAAAH2qKjDjWz71Dut10ZBTL+vn0NH3viK5Hy92gYqUawX0wAAAA8AAAAMdGlja19zcGFjaW5nAAAABAAAADwAAAAPAAAABnRva2VuMAAAAAAAEgAAAAEltPzYWa7C+mNIQ4xImzw8EMmLbSG+T9PLMMtolT75dwAAAA8AAAAGdG9rZW4xAAAAAAASAAAAAa3vzlmu5Slo92Bh1JTCUlt1ZZ+kKWpl9JnvKeVkd+SW"

	// goldenMint / goldenBurn — position lifecycle bodies from the same
	// pool at ledgers 61,487,383 and 61,487,425. Recognized, gated, and
	// deliberately projected as zero rows.
	goldenMint = "AAAAEQAAAAEAAAAHAAAADwAAAAZhbW91bnQAAAAAAAkAAAAAAAAAAAAAAAAdkijeAAAADwAAAAdhbW91bnQwAAAAAAkAAAAAAAAAAAAAAAAF9eEAAAAADwAAAAdhbW91bnQxAAAAAAkAAAAAAAAAAAAAAAABFjAlAAAADwAAAAVvd25lcgAAAAAAABIAAAABIzovoLDzgMm/PSicyUIChIApn2d5n/jeVHAlcu+O3HoAAAAPAAAABnNlbmRlcgAAAAAAEgAAAAAAAAAAih9xY+uv696Qtzi7gJ+IDuiXRUzlDY7kBXw71cxfN7sAAAAPAAAACnRpY2tfbG93ZXIAAAAAAAT//7akAAAADwAAAAp0aWNrX3VwcGVyAAAAAAAE///EtA=="
	goldenBurn = "AAAAEQAAAAEAAAAGAAAADwAAAAZhbW91bnQAAAAAAAkAAAAAAAAAAAAAAAA7JFG7AAAADwAAAAdhbW91bnQwAAAAAAkAAAAAAAAAAAAAAAAL68H/AAAADwAAAAdhbW91bnQxAAAAAAkAAAAAAAAAAAAAAAACLGBHAAAADwAAAAVvd25lcgAAAAAAABIAAAABIzovoLDzgMm/PSicyUIChIApn2d5n/jeVHAlcu+O3HoAAAAPAAAACnRpY2tfbG93ZXIAAAAAAAT//7akAAAADwAAAAp0aWNrX3VwcGVyAAAAAAAE///EtA=="
)

// Real identities from the same lake rows.
const (
	mainPool   = "CCR2CH4GQVCZHG7CHFVMNANCK45CU5DVKXZIIITDZQAU3CEJZ7RQH2MQ"
	tokenXLM   = "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA"
	tokenUSDC  = "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75"
	swapTxHash = "33ccf403dad3dffc350d1a9122aed3e24c01ba039fcdf7ca5665dd8762821b8d"
)
