package auth

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/RatesEngine/rates-engine/internal/cachekeys"
)

// APIKeyStore is the WRITER side of the API-key persistence
// interface. [APIKeyValidator] is the read path; the two are
// deliberately separated so the validator (hot path on every
// request) can be wired without exposing the mutating surface to
// non-admin callers.
//
// Implementations must be safe for concurrent use.
type APIKeyStore interface {
	// Create issues a fresh API key for the supplied request data.
	// The plaintext key is returned ONCE and is unrecoverable
	// thereafter — callers must echo it to the requester before
	// dropping the response.
	//
	// req carries the operator-supplied fields (Identifier, Label,
	// Tier, Scopes, RateLimitPerMin, ExpiresAt). The store fills
	// in KeyID + CreatedAt and generates the plaintext.
	//
	// Returns the public-safe APIKeyRecord (without the plaintext)
	// alongside the plaintext. Callers must not log or persist
	// the plaintext beyond the one-shot response body.
	Create(ctx context.Context, req CreateAPIKeyRequest) (rec APIKeyRecord, plaintext string, err error)
}

// CreateAPIKeyRequest is the payload [APIKeyStore.Create] consumes.
// The store ignores fields it computes itself (KeyID, CreatedAt).
type CreateAPIKeyRequest struct {
	// Identifier — owner-account reference. The store stamps this
	// onto APIKeyRecord.Identifier verbatim. Required.
	Identifier string

	// Label — customer-supplied human-readable name. Surfaced via
	// /v1/account/me. Optional.
	Label string

	// Tier — defaults to [TierAPIKey] when zero.
	Tier Tier

	// Scopes — optional capability list. Reserved for future
	// per-endpoint scope checks.
	Scopes []string

	// RateLimitPerMin — non-zero overrides the per-tier default.
	// Zero means "use the tier default".
	RateLimitPerMin int

	// ExpiresAt — zero means never.
	ExpiresAt time.Time
}

// RedisAPIKeyStore implements [APIKeyStore] against the same
// `apikey:<sha256-hex>` shape that [RedisAPIKeyValidator] reads.
//
// The store is the source of truth for issuance — it generates the
// plaintext (32 bytes from crypto/rand, hex-encoded with the `rek_`
// prefix) and the KeyID (8 bytes from crypto/rand, hex-encoded with
// the `kid_` prefix). The KeyID is distinct from the secret hash so
// it can appear in logs and customer-facing responses safely.
type RedisAPIKeyStore struct {
	rdb redis.Cmdable
	now func() time.Time
	// randRead is the entropy source — overridable in tests so the
	// test suite can pin generated key/KeyID bytes for the hash
	// stability assertions.
	randRead func([]byte) (int, error)
}

// StoreOption configures a [RedisAPIKeyStore] at construction.
type StoreOption func(*RedisAPIKeyStore)

// WithStoreClock overrides the time source for CreatedAt stamping.
// Production uses time.Now; tests inject a fixed clock.
func WithStoreClock(now func() time.Time) StoreOption {
	return func(s *RedisAPIKeyStore) { s.now = now }
}

// withRandRead overrides the entropy source. Internal — tests use
// it to pin generated bytes; production has no reason to override
// crypto/rand.
func withRandRead(fn func([]byte) (int, error)) StoreOption {
	return func(s *RedisAPIKeyStore) { s.randRead = fn }
}

// NewRedisAPIKeyStore constructs a store. rdb MUST be non-nil — the
// store is only wired when Redis is reachable; the API binary's
// auth layer falls back to the Noop validator (so requests 503)
// when Redis is missing, and the issuance endpoints simply 503 by
// not being mounted at all.
func NewRedisAPIKeyStore(rdb redis.Cmdable, opts ...StoreOption) *RedisAPIKeyStore {
	if rdb == nil {
		panic("auth: NewRedisAPIKeyStore: rdb must not be nil")
	}
	s := &RedisAPIKeyStore{
		rdb:      rdb,
		now:      time.Now,
		randRead: rand.Read,
	}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// Create implements [APIKeyStore].
//
// Workflow:
//
//  1. Validate request (Identifier required).
//  2. Generate KeyID (`kid_<16-hex>`) and plaintext (`rek_<64-hex>`).
//  3. Build APIKeyRecord with stamped CreatedAt and tier-defaulted Tier.
//  4. SET apikey:<sha256(plaintext)> JSON. SETNX semantics aren't
//     needed — the SHA-256 collision domain is astronomical and
//     the KeyID is independently unique.
//  5. Return (record, plaintext).
//
// On Redis I/O failure the plaintext is not surfaced (caller
// receives an empty string + the error). The record is also empty.
func (s *RedisAPIKeyStore) Create(ctx context.Context, req CreateAPIKeyRequest) (APIKeyRecord, string, error) {
	if req.Identifier == "" {
		return APIKeyRecord{}, "", errors.New("auth: Create: Identifier is required")
	}

	keyID, err := generateID(s.randRead, "kid_", 8)
	if err != nil {
		return APIKeyRecord{}, "", fmt.Errorf("auth: Create: generate key_id: %w", err)
	}
	plaintext, err := generateID(s.randRead, "rek_", 32)
	if err != nil {
		return APIKeyRecord{}, "", fmt.Errorf("auth: Create: generate plaintext: %w", err)
	}

	tier := req.Tier
	if tier == "" {
		tier = TierAPIKey
	}

	rec := APIKeyRecord{
		KeyID:           keyID,
		Identifier:      req.Identifier,
		Label:           req.Label,
		Tier:            tier,
		Scopes:          req.Scopes,
		RateLimitPerMin: req.RateLimitPerMin,
		CreatedAt:       s.now().UTC(),
		ExpiresAt:       req.ExpiresAt,
	}
	body, err := json.Marshal(rec)
	if err != nil {
		// Should be unreachable — APIKeyRecord has no func/chan
		// fields. Wrap for diagnostic completeness.
		return APIKeyRecord{}, "", fmt.Errorf("auth: Create: marshal record: %w", err)
	}

	hash := hashAPIKey(plaintext)
	// No TTL: keys live until explicitly deleted. Expiry +
	// revocation are encoded in the JSON record so the validator
	// can return the right sentinel error.
	if err := s.rdb.Set(ctx, cachekeys.APIKey(hash), body, 0).Err(); err != nil {
		return APIKeyRecord{}, "", fmt.Errorf("auth: Create: redis set: %w", err)
	}
	return rec, plaintext, nil
}

// generateID reads n bytes from rnd and returns prefix + hex(bytes).
func generateID(rnd func([]byte) (int, error), prefix string, n int) (string, error) {
	buf := make([]byte, n)
	read, err := rnd(buf)
	if err != nil {
		return "", err
	}
	if read != n {
		return "", fmt.Errorf("auth: short read from entropy source: got %d want %d", read, n)
	}
	return prefix + hex.EncodeToString(buf), nil
}

// Compile-time check.
var _ APIKeyStore = (*RedisAPIKeyStore)(nil)
