package config

import (
	"fmt"
	"io"
	"reflect"
	"strings"
	"time"
)

// SchemaField is one row in the generated reference — the flat,
// dotted form an operator would look up.
type SchemaField struct {
	Path     string // e.g. "region.id"
	Type     string // Go type label ("string", "int", "[]string", …)
	Default  string // from `default:"…"` tag; empty if none
	Env      string // from `env:"…"` tag; empty if none
	Doc      string // from `doc:"…"` tag; required
	Required bool   // true if no default supplied
}

// Describe walks the struct and returns every leaf field as a
// SchemaField. Nested substructs are flattened with dots in Path.
// Panics on a leaf field missing the `doc:` tag — the whole point
// of the exercise is to force docs.
func Describe() []SchemaField {
	return describe(reflect.TypeOf(Config{}), "")
}

func describe(t reflect.Type, prefix string) []SchemaField {
	var out []SchemaField
	for i := 0; i < t.NumField(); i++ {
		out = append(out, describeField(t.Field(i), prefix)...)
	}
	return out
}

// describeField returns 1+ rows for one struct field. Containers
// (struct, map[string]struct, []struct) flatten into per-leaf rows
// plus one row for the container itself; scalar leaves return a
// single row.
func describeField(f reflect.StructField, prefix string) []SchemaField {
	tomlName := f.Tag.Get("toml")
	if tomlName == "" {
		tomlName = strings.ToLower(f.Name)
	}
	path := tomlName
	if prefix != "" {
		path = prefix + "." + tomlName
	}
	if f.Type.Kind() == reflect.Struct && f.Type != reflect.TypeOf(time.Time{}) {
		return describe(f.Type, path)
	}
	if isMapStringStruct(f.Type) {
		return mapContainerRows(f, path)
	}
	if isSliceOfStruct(f.Type) {
		return sliceContainerRows(f, path)
	}
	return []SchemaField{leafRow(f, path)}
}

func isMapStringStruct(t reflect.Type) bool {
	return t.Kind() == reflect.Map &&
		t.Key().Kind() == reflect.String &&
		t.Elem().Kind() == reflect.Struct
}

func isSliceOfStruct(t reflect.Type) bool {
	return t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Struct
}

func mapContainerRows(f reflect.StructField, path string) []SchemaField {
	row := containerRow(f, path, "map[string]"+f.Type.Elem().Name(), "map field")
	return append([]SchemaField{row}, describe(f.Type.Elem(), path+".<key>")...)
}

func sliceContainerRows(f reflect.StructField, path string) []SchemaField {
	row := containerRow(f, path, "[]struct", "slice field")
	return append([]SchemaField{row}, describe(f.Type.Elem(), path+"[]")...)
}

func containerRow(f reflect.StructField, path, typeLabel, label string) SchemaField {
	doc := f.Tag.Get("doc")
	if doc == "" {
		panic(fmt.Sprintf("config schema: %s %s missing required `doc:` tag", label, path))
	}
	def := f.Tag.Get("default")
	return SchemaField{
		Path:     path,
		Type:     typeLabel,
		Default:  def,
		Env:      f.Tag.Get("env"),
		Doc:      doc,
		Required: def == "",
	}
}

func leafRow(f reflect.StructField, path string) SchemaField {
	doc := f.Tag.Get("doc")
	if doc == "" {
		panic(fmt.Sprintf("config schema: field %s is missing the required `doc:` tag", path))
	}
	def := f.Tag.Get("default")
	return SchemaField{
		Path:     path,
		Type:     typeLabel(f.Type),
		Default:  def,
		Env:      f.Tag.Get("env"),
		Doc:      doc,
		Required: def == "",
	}
}

func typeLabel(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Slice:
		return "[]" + typeLabel(t.Elem())
	case reflect.Ptr:
		return "*" + typeLabel(t.Elem())
	default:
		return t.Kind().String()
	}
}

// EmitMarkdown writes the reference doc to w. The output starts with
// the required `<!-- GENERATED FILE - DO NOT EDIT -->` banner so
// lint-docs.sh §7 is happy; regen via
// `go run ./cmd/ratesengine-ops docs-config > docs/reference/config/README.md`.
func EmitMarkdown(w io.Writer) error {
	fields := Describe()

	header := `<!-- GENERATED FILE - DO NOT EDIT -->
<!-- Source: internal/config/config.go -->
<!-- Regen:  make docs-config -->

# Rates Engine — Configuration Reference

This file is **generated** from the struct tags in
` + "`internal/config/config.go`" + ` and regenerated by the
` + "`docs-config`" + ` subcommand of ` + "`ratesengine-ops`" + `.

To add / rename / remove a config option:

1. Edit ` + "`internal/config/config.go`" + ` (struct field + tags).
2. ` + "`make docs-config`" + ` (regenerates this file).
3. Commit both in the same PR.

Operators hand-edit a TOML file that maps onto this schema.
Secrets never live in the TOML file itself — reference them via
the ` + "`env:`" + ` column.

## Top-level sections

`

	if _, err := io.WriteString(w, header); err != nil {
		return err
	}

	// Group fields by top-level section for readability.
	sections := groupByTopLevel(fields)

	for _, section := range sections {
		if _, err := fmt.Fprintf(w, "\n### `[%s]`\n\n", section.name); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "| Key | Type | Default | Env override | Description |\n"); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "| --- | ---- | ------- | ------------ | ----------- |\n"); err != nil {
			return err
		}
		for _, f := range section.fields {
			def := f.Default
			if def == "" {
				def = "_(required)_"
			} else {
				def = "`" + def + "`"
			}
			env := "—"
			if f.Env != "" {
				env = "`" + f.Env + "`"
			}
			if _, err := fmt.Fprintf(w, "| `%s` | `%s` | %s | %s | %s |\n",
				f.Path, f.Type, def, env, f.Doc); err != nil {
				return err
			}
		}
	}

	return nil
}

type section struct {
	name   string
	fields []SchemaField
}

func groupByTopLevel(fields []SchemaField) []section {
	order := []string{}
	bySection := map[string][]SchemaField{}
	for _, f := range fields {
		top := strings.SplitN(f.Path, ".", 2)[0]
		if _, seen := bySection[top]; !seen {
			order = append(order, top)
		}
		bySection[top] = append(bySection[top], f)
	}
	out := make([]section, 0, len(order))
	for _, name := range order {
		out = append(out, section{name: name, fields: bySection[name]})
	}
	return out
}
