#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_NOTICES.txt (and its explorer copy).

Go: modules linked into ./cmd/... for linux/amd64, license text read from the
module cache. npm: web/explorer production deps from `pnpm licenses list`.
Platform-specific optional packages (e.g. *-darwin-arm64) are skipped because
they differ per install host and would make the output non-reproducible.

Run via `make third-party-notices`; CI diffs the result.
"""
import json
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUTS = ["THIRD_PARTY_NOTICES.txt", "web/explorer/public/THIRD_PARTY_NOTICES.txt"]
LICENSE_FILE = re.compile(r"^(licen[sc]e|copying|unlicense|notice)(\.|$|-)", re.I)
PLATFORM = re.compile(r"-(darwin|linux|linuxmusl|win32|freebsd|openbsd|android)-")
COPYLEFT = re.compile(
    r"GNU (Affero |Lesser |Library )?General Public License|Server Side Public License", re.I
)


def run(cmd, cwd, env=None):
    e = dict(os.environ, **(env or {}))
    return subprocess.run(cmd, cwd=cwd, env=e, check=True, capture_output=True, text=True).stdout


def read_licenses(d):
    parts = []
    for name in sorted(os.listdir(d)):
        p = os.path.join(d, name)
        if os.path.isfile(p) and LICENSE_FILE.match(name):
            with open(p, encoding="utf-8", errors="replace") as f:
                parts.append((name, f.read().strip()))
    return parts


def entry(name, version, spec, d):
    if not os.path.isdir(d):
        sys.exit(f"{name} {version}: package dir {d} missing (run pnpm install / go mod download)")
    lic = read_licenses(d)
    body = "\n\n".join(t for _, t in lic) or "(no license file shipped in the package)"
    flag = ""
    if COPYLEFT.search(body) or re.search(r"GPL|SSPL", spec or ""):
        flag = "  [COPYLEFT-REVIEW]"
    return f"{name} {version}\nLicense: {spec or 'see text'}{flag}\n\n{body}\n"


def go_entries():
    env = {"GOOS": "linux", "GOARCH": "amd64", "CGO_ENABLED": "0", "GOFLAGS": "-mod=readonly"}
    run(["go", "mod", "download"], ROOT, env)
    out = run(
        ["go", "list", "-deps", "-f",
         "{{with .Module}}{{if not .Main}}{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}{{end}}", "./cmd/..."],
        ROOT, env)
    mods = sorted({tuple(l.split("\t")) for l in out.splitlines() if l})
    return [entry(p, v, None, d) for p, v, d in mods]


def npm_entries():
    out = run(["pnpm", "licenses", "list", "--prod", "--json"], os.path.join(ROOT, "web/explorer"))
    seen = {}
    for spec, pkgs in json.loads(out).items():
        for p in pkgs:
            if PLATFORM.search(p["name"]):
                continue
            for v, path in zip(p["versions"], p["paths"]):
                seen[(p["name"], v)] = (spec, path)
    return [entry(n, v, s, d) for (n, v), (s, d) in sorted(seen.items())]


def main():
    sep = "\n" + "-" * 72 + "\n"
    text = (
        "Third-party notices\n\n"
        "Stellar Index is Apache-2.0. It links or bundles the components below.\n"
        "Generated by scripts/dev/third-party-notices.py; do not edit.\n"
        "\n=== Go modules (linked into the stellarindex-* binaries) ===\n" + sep
        + sep.join(go_entries())
        + "\n=== npm packages (web/explorer production dependencies) ===\n" + sep
        + sep.join(npm_entries())
    )
    for o in OUTS:
        with open(os.path.join(ROOT, o), "w", encoding="utf-8") as f:
            f.write(text)
    flagged = [l for l in text.splitlines() if "[COPYLEFT-REVIEW]" in l]
    print(f"wrote {len(OUTS)} files; {len(flagged)} copyleft-flagged entries", file=sys.stderr)


main()
